use SecureElementPasses for iOS > 13.4
qiwi/apple-pay-in-app-provisioning-utils pull request #2
Opened 2021-06-30 11:28 UTC by viikufa

2021-07-02 09:24 UTC, Spetruk requested changes

2021-07-02 09:24 UTC, Spetruk commented on InAppProvisioningUtils/Classes/PassKitCardDetector.swift
> +            let findedBank = bankName == nil ? bankNames.contains(pass.organizationName) : pass.organizationName == bankName
Привет! Спасибо большое за пр, можешь заменить findedBank на foundBank?

2021-07-02 09:24 UTC, Spetruk commented on InAppProvisioningUtils/Classes/PassKitCardDetector.swift
> +public extension PassKitCardDetector {
public можно убрать, раз все методы private

2021-07-05 12:45 UTC, viikufa commented
@Spetruk  в публичных инициализаторах структур возникла необходимость для моков методов в unit tests. Думаю не критично открытие инициализатора?

2021-07-06 09:54 UTC, Spetruk commented
> @Spetruk в публичных инициализаторах структур возникла необходимость для моков методов в unit tests. Думаю не критично открытие инициализатора?

Да норм)

2021-07-15 11:43 UTC, Spetruk approved these changes

2021-07-15 11:43 UTC, merged